name: Publish Nuget Package

on:
  push:
    branches:
      - "v1*"
    paths-ignore:
      - '**/README.md'
      - '**/demo/**'
  pull_request: 
    branches:
      - "v1*"
    paths-ignore:
        - '**/README.md'
        - '**/demo/**'
defaults:
  run:
    working-directory: src
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: dotnet/nbgv@master
      id: nbgv
    - run: echo "VERSION=${{ steps.nbgv.outputs.SemVer2 }}" >> $GITHUB_ENV
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore /p:Version=$VERSION --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: pack nuget packages
      run: dotnet pack --output nupkgs --no-restore --no-build /p:PackageVersion=$VERSION --configuration Release
    - name: upload nuget package
      run: dotnet nuget push nupkgs/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json